### ISSUE TITLE
自定义浏览器 滚动条 的基本样式

### ISSUE THREAD

**Issue by mrlmx** [FeNature/css#2]
```css
.div-wrapper{
  height:300px;
  width: 300px;
  overflow-y:auto;
}
.div-wrapper::-webkit-scrollbar {/*滚动条整体样式*/
  width: 4px;     /*高宽分别对应横竖滚动条的尺寸*/
  height: 4px;
}
.div-wrapper::-webkit-scrollbar-thumb {/*滚动条里面小方块*/
  border-radius: 5px;
  -webkit-box-shadow: inset 0 0 5px rgba(0,0,0,0.2);
  background: rgba(0,0,0,0.2);
}
.div-wrapper::-webkit-scrollbar-track {/*滚动条里面轨道*/
  -webkit-box-shadow: inset 0 0 5px rgba(0,0,0,0.2);
  border-radius: 0;
  background: rgba(0,0,0,0.1);
}
```
[codePen 在线演示](https://codepen.io/lmx/pen/MZKPJY?editors=1111)
